openapi: 3.0.0
info:
  title: User Login API
  description: API for user login
  version: 1.0.0
servers:
  - url: https://bb.gs.com
paths:
  /login:
    post:
      summary: User Login
      description: Authenticate user credentials and retrieve access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
